WIP: Blurt Integration
dtube/dtube pull request #332
Opened 2021-09-23 02:15 UTC by eastmaels

2021-09-29 12:42 UTC, brishtiteveja commented
Please write some descriptions explaining the motivation and implementation.

2021-09-29 12:45 UTC, brishtiteveja requested changes
Looks pretty okay to me other than some integration issue.

2021-09-29 12:45 UTC, brishtiteveja commented on client/collections/videos.js
> +  if (!isComment && !newVideo) return
fix indentation in this if/else block

2021-09-29 14:38 UTC, eastmaels commented on client/collections/videos.js
> +  if (!isComment && !newVideo) return
Thanks for the review. Fixed indention.

2021-11-14 23:17 UTC, tibfox commented
are thise requested changes still open or can we finally merge that?

2021-11-29 08:47 UTC, eastmaels commented
> are thise requested changes still open or can we finally merge that?

I've already resolved the requested changes and have pushed additional changes requested by @d00k13 via discord.

2021-11-29 12:43 UTC, techcoderx approved these changes

2021-12-02 02:56 UTC, merged

2021-12-02 20:21 UTC, brishtiteveja commented
If this is approved by @techcoderx, may be we can merge.